import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import ToastComponent from "./components/toaster/ToastComponent";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import Home from "./components/initial/Initial";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/utils/authOptions";
import HeaderAdmin from "./components/admin/header/HeaderAdmin";
import { PrismaClient } from "@prisma/client";
import { fetchCategory } from "@/actions/actions";
import HeaderInitial from "./headerInitial/page";
import WhatsappButton from "./components/Buttons/whatsapp";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Masterjus",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  const prisma = new PrismaClient();
  /*const menuItens = await prisma.menuItems.findMany({
    include: {
      category: {
        select: {
          NomeCat: true, 
        }, 
      },
    },
  }); */
 // const filteredMenuItems = menuItens.filter(item => item.category !== null);
  
  const session = await getServerSession(authOptions);
  if (session?.user?.role === "ADMIN") {
    return (
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <HeaderAdmin />
            {children}
            <ToastComponent />
          </Providers>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HeaderInitial />
          {children}
          <Footer />
        {/* menuItems={filteredMenuItems}/> */}
          <WhatsappButton className="fixed bottom-4 left-4 z-50" />
          <ToastComponent />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
